---
- name: Converge
  hosts: all

  vars_files:
    - vars.yml

  vars:
    optional_vars_file: "{{ lookup('first_found', '~/secrets.yml', errors='ignore') }}"

  pre_tasks:
    - name: Update repositories cache
      package:
        update_cache: yes

  tasks:
    - name: optional_vars_file
      include_vars: "{{ optional_vars_file }}"
      when: optional_vars_file is file
    - name: "Include fabiokleis.postfix_example"
      include_role:
        name: "postfix_example"
