---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: postfixtest
    image: "geerlingguy/docker-debian9-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansiblelint .
