---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: postfixtest
    image: "geerlingguy/docker-debian10-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ~/.vault
      #ask_vault_pass: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansiblelint .
