---
# tasks file for postfix_example
- name: Install packages to debug
  apt:
    name: 
      - swaks
      - vim
      - git
      - net-tools
      - dnsutils
      - telnet
    state: present
    update_cache: yes

- name: Create a smtpd configuration to postfix sasl
  template:
    src: smtpd.conf.j2
    dest: "{{ smtpd_sasl_dir }}/smtpd.conf"
  notify:
    - Restart saslauthd
    - Restart postfix

- name: Add postfix user to sasl
  user:
    name: postfix
    groups: sasl
    append: yes
    state: present

- name: Add user to send test mails
  user:
    name: "{{ mailtester_name }}"
    password: "{{ mailtester_password }}"
    state: present

- name: Setup a separated saslauthd process to be used from Postfix
  template:
    src: saslauthd-postfix.j2
    dest: "{{ saslauthd_default_path }}/saslauthd-postfix"
  notify:
    - Restart saslauthd
    - Restart postfix
    - Restart postmap

