---
# tasks file for postfix_example
- name: Install packages to debug
  apt:
    name: 
      - swaks
      - vim
      - git
      - net-tools
      - dnsutils
    state: present
    update_cache: yes
  notify:
    - Restart saslauthd
    - Restart postfix

- name: Create a smtpd configuration to postfix sasl
  template:
    src: smtpd.conf.j2
    dest: "{{ smtpd_sasl_dir }}/smtpd.conf"
  notify:
    - Restart saslauthd
    - Restart postfix
