---
# tasks file for postfix_example
- name: Install packages to debug
  apt:
    name: 
      - swaks
      - vim
      - git
      - net-tools
      - dnsutils
    state: present
    update_cache: yes
  notify:
    - Restart saslauthd
    - Restart postfix

- name: Create a smtpd configuration to postfix sasl
  template:
    src: smtpd.conf.j2
    dest: "{{ smtpd_sasl_dir }}/smtpd.conf"
  notify:
    - Restart saslauthd
    - Restart postfix

- name: Setup a sepate saslauthd process to be used from Postfix
  template:
    src: saslauthd-postfix.j2
    dest: "{{ saslauthd_default_path }}/saslauthd-postfix"

- name: Add postfix user to sasl
  user:
    name: postfix
    group: sasl

- name: Set socket path to communicate between saslauthd instance and Postfix
  shell: |
    rm /run/saslauthd
    ln -s {{ chroot_dir }} /run/saslauthd
    dpkg-statoverride --add root sasl 710 {{ chroot_dir }}
  notify:
    - Restart saslauthd
    - Restart postfix
