---
- name: Apply postfix example
  hosts: postfix_example
  become: yes
  pre_tasks:
    - name: Update repositories cache
      package:
        update_cache: yes

  roles:
    - role: postfix_example
  vars:
    postfix_raw_options:
      - "smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination"
      - "smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt"
      - "smtp_tls_security_level = encrypt"
      - "cyrus_sasl_config_path = /etc/postfix/sasl"
      - "broken_sasl_auth_clients = yes"
      - "smtpd_sasl_auth_enable = yes"
      - "smtpd_sasl_security_options = noanonymous"
      - "smtpd_sasl_local_domain = $myhostname"
