---
# handlers file for postfix_example
- name: Restart postfix
  service:
    name: postfix
    state: restarted
    enabled: true

- name: Restart saslauthd
  service:
    name: saslauthd
    state: restarted
    enabled: true

- name: Restart postmap
  shell: |
    sudo chown postfix /etc/postfix
    postmap /etc/postfix/sasl_passwd
